
import { propertyData } from "@/app/types/property/propertyData";
import { NextResponse } from "next/server";

const property: propertyData[] = [
  // Appartment
  {
    id: '1',
    property_img: "/images/properties/PROP1.JPG",
    property_title: "Nueva Camahuiroa",
    property_price: "Desde $98,975",
    category: "Nueva Camahuiroa",
    category_img: "/images/property_option/sinaloa.png",
    rooms: 2,
    bathrooms: 1,
    location: "Huatabampo, Sonora",
    livingArea: " 200m² en adelante",
    tag: "Quiero saber más",
    check: true,
    status: "Buy",
    type: "Apartment",
    beds: 2,
    garages: 0,
    region: "south",
    name: "Property 1",
    slug: "modern-apartment"
  },
  {
    id: '2',
    property_img: "/images/properties/prop2.jpg",
    property_title: "Nuevo Paraíso",
    property_price: "Desde $96,835",
    category: "Nuevo Paraíso",
    category_img: "/images/property_option/rio.png",
    rooms: 3,
    bathrooms: 2,
    location: "San Blas, El Fuerte, Sinaloa",
    livingArea: "200m² en adelante",
    tag: "Dame más información",
    check: true,
    status: "Buy",
    type: "Nuevo Paraíso",
    beds: 3,
    garages: 1,
    region: "north",
    name: "Property 2",
    slug: "city-apartment"
  },
  {
    id: '3',
    property_img: "/images/properties/naay.jpg",
    property_title: "Aldea Naay",
    property_price: "Desde $96,835",
    category: "Aldea Naay",
    category_img: "/images/property_option/lago.png",
    rooms: 4,
    bathrooms: 3,
    location: "Mazatlán, Sinaloa",
    livingArea: "200m² en adelante",
    tag: "Esto si me interesa",
    check: true,
    status: "Buy",
    type: "Apartment",
    beds: 4,
    garages: 1,
    region: "east",
    name: "Property 3",
    slug: "luxury-apartment"
  },
  {
    id: '4',
    property_img: "/images/properties/cartagena.jpeg",
    property_title: "Cartagena",
    property_price: "$106,575",
    category: "Cartagena de Indias",
    category_img: "/images/property_option/cultivo.png",
    rooms: 3,
    bathrooms: 2,
    location: "Mazatlán, Sinaloa",
    livingArea: "200m² en adelante",
    tag: "Estoy interesade",
    check: true,
    status: "Buy",
    type: "House",
    beds: 3,
    garages: 1,
    region: "north",
    name: "Property 4",
    slug: "mithra-villa"
  },
  {
    id: '5',
    property_img: "/images/properties/huatulco.jpeg",
    property_title: "Nuevo Huatulco",
    property_price: "$99,500",
    category: "Nuevo Huatulco",
    category_img: "/images/property_option/huatulco.png",
    rooms: 4,
    bathrooms: 3,
    location: "Santa María Huatulco, Oaxaca",
    livingArea: "200m² en adelante",
    tag: "Quiero saber más",
    check: false,
    status: "Buy",
    type: "House",
    beds: 4,
    garages: 2,
    region: "west",
    name: "Property 5",
    slug: "palm-villa"
  },
  {
    id: '6',
    property_img: "/images/properties/monaco.jpeg",
    property_title: "Hacienda Mónaco",
    property_price: "$95,025",
    category: "Hacienda Mónaco",
    category_img: "/images/property_option/monaco.png",
    rooms: 5,
    bathrooms: 4,
    location: "Mazatlán, Sinaloa",
    livingArea: "200m² en adelante",
    tag: "Estoy muy interesado/a",
    check: true,
    status: "Buy",
    type: "House",
    beds: 5,
    garages: 2,
    region: "south",
    name: "Property 6",
    slug: "sunset-villa"
  },
  {
    id: '7',
    property_img: "/images/properties/napoles2.jpeg",
    property_title: "Hacienda Nápoles 2",
    property_price: "$106,575",
    category: "Hacienda Nápoles 2",
    category_img: "/images/property_option/napoles2.png",
    rooms: 6,
    bathrooms: 2,
    location: "Mazatlán, Sinaloa",
    livingArea: "200m² en adelante",
    tag: "Deseo más información",
    check: true,
    status: "Buy",
    type: "Commercial",
    beds: 2,
    garages: 2,
    region: "central",
    name: "Property 7",
    slug: "downtown-office"
  },
  {
    id: '8',
    property_img: "/images/properties/celestino.jpeg",
    property_title: "Nuevo Celestino",
    property_price: "$$95,025",
    category: "Nuevo Celestino",
    category_img: "/images/property_option/celestino.png",
    rooms: 10,
    bathrooms: 4,
    location: "Celestino Gasca, La Cruz de Elota, Sinaloa",
    livingArea: "200m² en adelante",
    tag: "Explícame todo",
    check: true,
    status: "Buy",
    type: "Commercial",
    beds: 2,
    garages: 4,
    region: "north",
    name: "Property 8",
    slug: "it-office-space"
  }
];

export async function GET() {
  return NextResponse.json(property);
}
