
import { propertyData } from "@/app/types/property/propertyData";
import { NextResponse } from "next/server";

const property: propertyData[] = [
  // Appartment
  {
    id: '1',
    property_img: "/images/properties/PROP1.JPG",
    property_title: "Nueva Camahuiroa",
    property_price: "Desde $98,975",
    category: "Nueva Camahuiroa",
    category_img: "/images/property_option/sinaloa.png",
    rooms: 2,
    bathrooms: 1,
    location: "Huatabampo, Sonora",
    livingArea: " 200m² en adelante",
    tag: "Quiero saber más",
    check: true,
    status: "Buy",
    type: "Apartment",
    beds: 2,
    garages: 0,
    region: "south",
    name: "NuevoCamahuiroa",
    slug: "nuevocamahuiroa"
  },
  {
    id: '2',
    property_img: "/images/properties/prop2.jpg",
    property_title: "Nuevo Paraíso",
    property_price: "Desde $96,835",
    category: "Nuevo Paraíso",
    category_img: "/images/property_option/rio.png",
    rooms: 3,
    bathrooms: 2,
    location: "San Blas, El Fuerte, Sinaloa",
    livingArea: "200m² en adelante",
    tag: "Dame más información",
    check: true,
    status: "Buy",
    type: "Nuevo Paraíso",
    beds: 3,
    garages: 1,
    region: "north",
    name: "Nuevo Paraíso",
    slug: "nuevoparaiso"
  },
  {
    id: '3',
    property_img: "/images/properties/naay.jpg",
    property_title: "Nuevo Orizaba",
    property_price: "Desde $132,252",
    category: "Nuevo Orizaba",
    category_img: "/images/property_option/orizaba.png",
    rooms: 4,
    bathrooms: 3,
    location: "Orizaba, Veracruz",
    livingArea: "200m² en adelante",
    tag: "Esto si me interesa",
    check: true,
    status: "Buy",
    type: "Apartment",
    beds: 4,
    garages: 1,
    region: "east",
    name: "Nuevo Orizaba",
    slug: "nuevorizaba"
  },
  {
    id: '4',
    property_img: "/images/properties/cartagena.jpeg",
    property_title: "Cartagena",
    property_price: "Desde $95,025",
    category: "Cartagena",
    category_img: "/images/property_option/cultivo.png",
    rooms: 3,
    bathrooms: 2,
    location: "Mazatlán, Sinaloa",
    livingArea: "200m² en adelante",
    tag: "Estoy interesade",
    check: true,
    status: "Buy",
    type: "House",
    beds: 3,
    garages: 1,
    region: "north",
    name: "Cartagena",
    slug: "cartagena"
  },
  {
    id: '5',
    property_img: "/images/properties/huatulco.jpeg",
    property_title: "Nuevo Huatulco",
    property_price: "Desde $96,835",
    category: "Nuevo Huatulco",
    category_img: "/images/property_option/huatulco.png",
    rooms: 4,
    bathrooms: 3,
    location: "Santa María Huatulco, Oaxaca",
    livingArea: "200m² en adelante",
    tag: "Quiero saber más",
    check: false,
    status: "Buy",
    type: "House",
    beds: 4,
    garages: 2,
    region: "west",
    name: "Nuevo Huatulco",
    slug: "nuevohuatulco"
  },
  {
    id: '6',
    property_img: "/images/properties/monaco.jpeg",
    property_title: "Hacienda Mónaco",
    property_price: "Desde $95,025",
    category: "Hacienda Mónaco",
    category_img: "/images/property_option/monaco.png",
    rooms: 5,
    bathrooms: 4,
    location: "Mazatlán, Sinaloa",
    livingArea: "200m² en adelante",
    tag: "Estoy muy interesado/a",
    check: true,
    status: "Buy",
    type: "House",
    beds: 5,
    garages: 2,
    region: "south",
    name: "Hacienda Mónaco",
    slug: "haciendamonaco"
  },
  {
    id: '8',
    property_img: "/images/properties/celestino.jpeg",
    property_title: "Nuevo Celestino",
    property_price: "Desde $95,025",
    category: "Nuevo Celestino",
    category_img: "/images/property_option/celestino.png",
    rooms: 10,
    bathrooms: 4,
    location: "Celestino Gasca, La Cruz de Elota, Sinaloa",
    livingArea: "200m² en adelante",
    tag: "Explícame todo",
    check: true,
    status: "Buy",
    type: "Commercial",
    beds: 2,
    garages: 4,
    region: "north",
    name: "Nuevo Celestino",
    slug: "nuevocelestino"
  },
  {
    id: '7',
    property_img: "/images/properties/napoles2.jpeg",
    property_title: "Hacienda Nápoles 1",
    property_price: "Desde $129,675",
    category: "Hacienda Nápoles 1",
    category_img: "/images/property_option/napoles2.png",
    rooms: 6,
    bathrooms: 2,
    location: "Mazatlán, Sinaloa",
    livingArea: "200m² en adelante",
    tag: "Deseo más información",
    check: true,
    status: "Buy",
    type: "Commercial",
    beds: 2,
    garages: 2,
    region: "central",
    name: "Property 7",
    slug: "haciendanapoles1"
  },
  {
    id: '8',
    property_img: "/images/properties/celestino.jpeg",
    property_title: "Nuevo Celestino",
    property_price: "Desde $95,025",
    category: "Nuevo Celestino",
    category_img: "/images/property_option/celestino.png",
    rooms: 10,
    bathrooms: 4,
    location: "Celestino Gasca, La Cruz de Elota, Sinaloa",
    livingArea: "200m² en adelante",
    tag: "Explícame todo",
    check: true,
    status: "Buy",
    type: "Commercial",
    beds: 2,
    garages: 4,
    region: "north",
    name: "Nuevo Celestino",
    slug: "nuevocelestino"
  },
    {
    id: '9',
    property_img: "/images/properties/napoles2.jpeg",
    property_title: "Hacienda Nápoles 2",
    property_price: "Desde $106,575",
    category: "Hacienda Nápoles 2",
    category_img: "/images/property_option/napoles2.png",
    rooms: 6,
    bathrooms: 2,
    location: "Mazatlán, Sinaloa",
    livingArea: "200m² en adelante",
    tag: "Deseo más información",
    check: true,
    status: "Buy",
    type: "Commercial",
    beds: 2,
    garages: 2,
    region: "central",
    name: "Hacienda Nápoles 2",
    slug: "haciendanapoles2"
  },
  {
    id: '10',
    property_img: "/images/properties/napoles2.jpeg",
    property_title: "Hacienda Nápoles 3",
    property_price: "Desde $106,575",
    category: "Hacienda Nápoles 3",
    category_img: "/images/property_option/napoles2.png",
    rooms: 6,
    bathrooms: 2,
    location: "Mazatlán, Sinaloa",
    livingArea: "200m² en adelante",
    tag: "Deseo más información",
    check: true,
    status: "Buy",
    type: "Commercial",
    beds: 2,
    garages: 2,
    region: "central",
    name: "Hacienda Nápoles 3",
    slug: "haciendanapoles3"
  },
];

export async function GET() {
  return NextResponse.json(property);
}
